# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wiretrustee < Formula
  desc "Wiretrustee project."
  homepage "https://wiretrustee.com/"
  version "0.2.0-beta.2"
  license "BSD3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/wiretrustee/wiretrustee/releases/download/v0.2.0-beta.2/wiretrustee_0.2.0-beta.2_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "73778b7253a5160815629055f2c165888403d78facf4211dd8384fa2fa3b0504"

      def install
        bin.install "wiretrustee"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/wiretrustee/wiretrustee/releases/download/v0.2.0-beta.2/wiretrustee_0.2.0-beta.2_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "d4c13d8c6fb9bb43e921f66655fc0c7284a58dd6a02d06817834d486041f1e0f"

      def install
        bin.install "wiretrustee"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/wiretrustee/wiretrustee/releases/download/v0.2.0-beta.2/wiretrustee_0.2.0-beta.2_linux_armv6.tar.gz", :using => CurlDownloadStrategy
      sha256 "5e32c4c19c9c36b42a9bab8e4b00953e9b9e4fc8597668d1e0fc1489cc635336"

      def install
        bin.install "wiretrustee"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/wiretrustee/wiretrustee/releases/download/v0.2.0-beta.2/wiretrustee_0.2.0-beta.2_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "8ea2ce3768c7c56c6c29fc412f32b9f12635ae2a9e83060823bc0f1ee18e636a"

      def install
        bin.install "wiretrustee"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wiretrustee/wiretrustee/releases/download/v0.2.0-beta.2/wiretrustee_0.2.0-beta.2_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "2be96e2046d22e4c4bf3cbbea362b638c911f833a6dff145f17ccc367143cc80"

      def install
        bin.install "wiretrustee"
      end
    end
  end

  test do
    system "#{bin}/wiretrustee -h"
  end
end
