# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wiretrustee < Formula
  desc "Wiretrustee project."
  homepage "https://wiretrustee.com/"
  version "0.2.0-beta.3"
  license "BSD3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/wiretrustee/wiretrustee/releases/download/v0.2.0-beta.3/wiretrustee_0.2.0-beta.3_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "6e1270c6b8582d841e135662f06de78458a8fa6085d18239f8e30715b79a69ad"

      def install
        bin.install "wiretrustee"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/wiretrustee/wiretrustee/releases/download/v0.2.0-beta.3/wiretrustee_0.2.0-beta.3_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "12decf7e48a830e020ace2c525b331f5913a63efd0e4beb38ed656fa98eb6c9e"

      def install
        bin.install "wiretrustee"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wiretrustee/wiretrustee/releases/download/v0.2.0-beta.3/wiretrustee_0.2.0-beta.3_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "f4b09fecf900138b362ac0370667fca14fab7f3baac76079b60f1cfd713ba8c5"

      def install
        bin.install "wiretrustee"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/wiretrustee/wiretrustee/releases/download/v0.2.0-beta.3/wiretrustee_0.2.0-beta.3_linux_armv6.tar.gz", :using => CurlDownloadStrategy
      sha256 "1f7db993aa861f152f18cab595b5acbb35b09b224d66553bbf56a1c908b61602"

      def install
        bin.install "wiretrustee"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/wiretrustee/wiretrustee/releases/download/v0.2.0-beta.3/wiretrustee_0.2.0-beta.3_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "48aa85b41c3a40887de6590f98a696e4eb464e247d2c4f529dc13371fe4481f5"

      def install
        bin.install "wiretrustee"
      end
    end
  end

  test do
    system "#{bin}/wiretrustee -h"
  end
end
